[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./play2study.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatters.generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
